default:
  image: python:3.7.6-alpine3.10
  script:
    - pip install --quiet --requirement tests/requirements.txt
    - pytest -vs
  variables:
    ATLAS_TOKEN: secret-token
  tags:
    - adeo-cloud
